on:
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # or adoptopenjdk

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: SonarCloud Scan (v2)
        uses: SonarSource/sonarcloud-github-action@v2
        with:
         args: >
          -Dsonar.projectKey=adolfcg_nebo
          -Dsonar.organization=Adolfo
          -Dsonar.sources=src
          -Dsonar.python.version=3.11
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
