name: Docker Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install semantic-release CLI and plugins
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/exec

      - name: Docker login
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
         java-version: '17'
         distribution: 'temurin'

      - name: Download SonarScanner CLI
        run: |
             curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
             unzip sonar-scanner.zip -d $HOME
             echo "$HOME/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_PATH

      - name: Run SonarScanner
        run: sonar-scanner
        env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this
          IMAGE_NAME: ghcr.io/${{ github.repository }}
        run: |
          semantic-release

      - name: Send Discord notification
        if: always()  # run whether success or failure
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"📦 *${{ github.repository }}* → `${{ github.workflow }}` **${{ job.status }}** on branch \`${{ github.ref_name }}\` by \`${{ github.actor }}\`\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

