name: Security Scan

on:
  pull_request:
    branches: [main]

jobs:
  deps-scan:
    name: Python Dependency Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Audit requirements
        run: pip-audit -r requirements.txt

  docker-scan:
    name: Docker Image Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: 1
